INTERNET_SLANG = {
    "mkr": "my kitchen rules",
    "adad": "another day another dollar",
    "adih": "another day in hell",
    "adip": "another day in paradise",
    "aeap": "as early as possible",
    "af": "as fuck",
    "afaicr": "as far as i can recall or remember",
    "afaics": "as far as i can see",
    "afaict": "as far as i can tell",
    "afaik": "as far as i know",
    "afair": "as far as i remember",
    "afaiu": "as far as i understand",
    "afaiui": "as far as i understand it",
    "afap": "as far as possible",
    "afk": "away from keyboard",
    "alol": "actually laughing out loud",
    "loll": "laughing out loud",
    "lol": "laughing out loud",
    "brb": "be right back",
    "idk": "i don't know",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "tbh": "to be honest",
    "smh": "shaking my head",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "omg": "oh my god",
    "ttyl": "talk to you later",
    "ikr": "i know right",
    "btw": "by the way",
    "fyi": "for your information",
    "gtg": "got to go",
    "nvm": "never mind",
    "np": "no problem",
    "wfh": "work from home",
    "yolo": "you only live once",
    "jk": "just kidding",
    "jfk": "just fucking kidding",
    "jfc": "jesus fucking christ",
    "tldr": "too long didn't read",
    "wyd": "what are you doing",
    "wbu": "what about you",
    "hmu": "hit me up",
    "bff": "best friends forever",
    "idc": "i don't care",
    "pov": "point of view",
    "ama": "ask me anything",
    "asap": "as soon as possible",
    "asl": "age sex location",
    "aslp": "age sex location picture",
    "ateotd": "at the end of the day",
    "atb": "all the best",
    "atfq": "answer the full question",
    "atm": "at the moment",
    "awol": "absent without official leave",
    "b2b": "business to business",
    "b2c": "business to customer",
    "b4": "before",
    "bbiab": "be back in a bit",
    "bbq": "barbecue",
    "bbl": "be back later",
    "bbs": "be back shortly",
    "bcnu": "be seeing you",
    "bf": "best friend or boyfriend",
    "bfn": "bye for now",
    "bofh": "bastard operator from hell",
    "bsod": "blue screen of death",
    "btdt": "been there done that",
    "bttt": "back to the top",
    "cmiiw": "correct me if i'm wrong",
    "cob": "close of business",
    "cu": "see you",
    "cya": "see you or cover your ass",
    "dftt": "don't feed the trolls",
    "dftba": "don't forget to be awesome",
    "dgaf": "don't give a fuck",
    "diaf": "die in a fire",
    "dilligaf": "does it look like i give a fuck",
    "dnd": "do not disturb",
    "doa": "dead on arrival",
    "eli5": "explain like i'm five",
    "esad": "eat shit and die",
    "f9": "fine",
    "faq": "frequently asked questions",
    "ffs": "for fuck's sake",
    "fmcdh": "from my cold dead hands",
    "fml": "fuck my life",
    "foad": "fuck off and die",
    "foaf": "friend of a friend",
    "ftfy": "fixed that for you",
    "ftr": "for the record",
    "ftl": "for the loss",
    "ftw": "for the win",
    "fu": "fuck you",
    "fubar": "fucked up beyond all recognition",
    "fud": "fear uncertainty and doubt",
    "fwiw": "for what it's worth",
    "gbtw": "get back to work",
    "gf": "girlfriend",
    "gfu": "good for you",
    "gfy": "go fuck yourself",
    "gg": "good game",
    "ggs": "good games",
    "giyf": "google is your friend",
    "gj": "good job",
    "gl": "good luck",
    "gmta": "great minds think alike",
    "gr8": "great",
    "gratz": "congratulations",
    "gtfo": "get the fuck out",
    "g2g": "got to go",
    "hbu": "how about you",
    "hand": "have a nice day",
    "hf": "have fun",
    "hth": "hope this helps",
    "ianal": "i am not a lawyer",
    "ibtl": "in before the lock",
    "idgaf": "i don't give a fuck",
    "ig": "i guess",
    "iht": "i had to",
    "iirc": "if i recall correctly",
    "iiuc": "if i understand correctly",
    "ily": "i love you",
    "imao": "in my arrogant opinion",
    "imnsho": "in my not so humble opinion",
    "inb4": "in before",
    "iow": "in other words",
    "irc": "internet relay chat",
    "irl": "in real life",
    "istm": "it seems to me",
    "itym": "i think you mean",
    "iwsn": "i want sex now",
    "iydmma": "if you don't mind my asking",
    "iykwim": "if you know what i mean",
    "jas": "just a sec",
    "jfgi": "just fucking google it",
    "jftr": "just for the record",
    "j/k": "just kidding",
    "jtlyk": "just to let you know",
    "fb": "facebook",
    "msg": "message",
    "paw": "parents are watching",
    "pitr": "parent in the room",
    "pbb": "parent behind back",
    "poms": "parent over my shoulder",
    "kpc": "keeping parents clueless",
    "pah": "parent at home",
    "hifw": "how i feel when",
    "tfw": "that feeling when",
    "mfw": "my face when",
    "mrw": "my reaction when",
    "ifyo": "i feel your pain",
    "tntl": "trying not to laugh",
    "zzz": "sleeping, bored, tired",
    "wywh": "wish you were here",
    "time": "tears in my eyes",
    "bae": "before anyone else",
    "fimh": "forever in my heart",
    "bsaaw": "big smile and a wink",
    "bwl": "bursting with laughter",
    "csl": "can't stop laughing",
    "ssdd": "same stuff, different day",
    "qq": "crying",
    "omdb": "over my dead body",
    "ynk": "you never know",
    "nth": "nice to have",
    "srsly": "seriously",
    "ygtr": "you got that right",
    "aymm": "are you my mother?",
    "cwot": "complete waste of time",
    "afaic": "as far as i'm concerned",
    "aamof": "as a matter of fact",
    "ymmv": "your mileage may vary",
    "dm": "direct message",
    "tl;dr": "too long; didn't read",
    "til": "today i learned",
    "omw": "on my way",
    "soml": "story of my life",
    "embm": "early morning business meeting",
    "j4f": "just for fun",
    "jsyk": "just so you know",
    "fawc": "for anyone who cares",
    "rlrt": "real life retweet",
    "oh": "overheard",
    "wuzup": "what's up?",
    "cs": "career suicide",
    "dwh": "during work hours",
    "w8": "wait",
    "nfs": "not for sale",
    "b4n": "bye for now",
    "b@u": "back at you",
    "bbbg": "bye bye be good",
    "bbias": "be back in a sec",
    "ruok": "are you ok?",
    "cyt": "see you tomorrow",
    "dbmib": "don't bother me i'm busy",
    "gfn": "gone for now",
    "nsfw": "not safe for work",
    "tmb": "tweet me back",
    "wtpa": "where the party at?",
    "dae": "does anyone else?",
    "prt": "please retweet",
    "ptb": "please text back",
    "tia": "thanks in advance",
    "bump": "bring up my post",
    "nsfl": "not safe for life",
    "sfw": "safe for work",
    "gras": "generally recognised as safe",
    "nbd": "not big deal",
    "oc": "original content",
    "4ao": "for adults only",
    "op": "original poster",
    "ppl": "people",
    "icymi": "in case you missed it",
    "jic": "just in case",
    "nagi": "not a good idea",
    "goi": "get over it",
    "rbtl": "read between the lines",
    "ayor": "at your own risk",
    "diy": "do it yourself",
    "e123": "easy as one, two, three",
    "gahoy": "get a hold of yourself",
    "stfu": "shut the f*** up",
    "tmi": "too much information",
    "lmk": "let me know",
    "byob": "bring your own beer",
    "bogo": "buy one get one",
    "jw": "just wondering",
    "tgif": "thank goodness it’s friday",
    "tbf": "to be frank",
    "rn": "right now",
    "iso": "in search of",
    "brt": "be right there",
    "bfd": "big freaking deal",
    "ngl": "not gonna lie",
    "bts": "behind the scenes",
    "tba": "to be announced",
    "tbd": "to be decided",
    "abt": "about",
    "iykyk": "if you know you know",
    "bc": "because",
    "fomo": "fear of missing out",
    "snafu": "situation normal, all f***** up",
    "h8": "hate",
    "myob": "mind your own business",
    "tlc": "tender loving care",
    "hbd": "happy birthday",
    "w/e": "whatever",
    "wtf": "what the f***",
    "wysiwyg": "what you see is what you get",
    "fwif": "for what it’s worth",
    "tw": "trigger warning",
    "goat": "greatest of all time",
    "eod": "end of day",
    "eow": "end of week",
    "eta": "estimated time of arrival",
    "cc": "send a copy to",
    "aka": "also known as",
    "n/a": "not applicable or not available",
    "ooo": "out of office",
    "wdyt": "what do you think?",
    "wygam": "when you get a minute",
    "csr": "corporate social responsibility",
    "dei": "diversity, equity, and inclusion",
    "p/e": "price-to-earnings ratio",
    "ebitda": "earnings before interest, taxes, depreciation, and amortization",
    "smp": "social media platform",
    "li": "linkedin",
    "yt": "youtube",
    "sc": "snapchat",
    "br": "bereal",
    "x": "previously named twitter",
    "wa": "whatsapp",
    "tt": "tiktok",
    "pin": "pinterest",
    "ttv": "twitch tv",
    "ff": "follow friday",
    "im": "instant message",
    "pm": "private message",
    "qotd": "quote of the day",
    "ootd": "outfit of the day",
    "rt": "retweet",
    "tbt": "throwback thursday",
    "fbf": "flashback friday",
    "grwm": "get ready with me",
    "tmw": "that moment when",
    "mcm": "man crush monday",
    "wcw": "woman crush wednesday",
    "lysm": "love you so much",
    "pda": "public display of affection",
    "ltr": "longterm relationship",
    "dtr": "define the relationship",
    "ldr": "long-distance relationship",
    "xoxo": "hugs and kisses",
    "otp": "one true pairing",
    "loml": "love of my life",
    "so": "significant other",
    "cta": "call to action",
    "ugc": "user-generated content",
    "ux": "user experience",
    "sms": "short message service",
    "mms": "multimedia messaging service",
    "rcs": "rich communication services",
    "roi": "return on investment",
    "ctr": "click-through rate",
    "cpc": "cost per click",
    "cr": "conversion rate",
    "smb": "small/medium business",
    "tos": "terms of service",
    "scn": "short code number",
    "5g": "5th generation, meaning the newest generation of mobile communications",
    "tcpa": "telephone consumer protection act"
}
