import jsPDF from "jspdf"
import html2canvas from "html2canvas"

/**
 * Exportă dashboard-ul ca PDF
 * @param {Object} options - Opțiuni pentru export
 * @param {string} options.filename - Numele fișierului PDF
 * @param {string} options.postTitle - Titlul postării
 * @param {string} options.postLink - Link-ul postării
 * @param {string} options.platform - Platforma (Facebook/TikTok)
 * @param {Object} options.analysisData - Datele analizei
 */
export async function exportDashboardToPDF(options = {}) {
  const {
    filename = "analysis-report.pdf",
    postTitle = "Social Media Analysis",
    postLink = "",
    platform = "Unknown",
    analysisData = null,
  } = options

  try {
    // Afișează loading indicator
    showExportLoading(true)

    // 1. Capturează dashboard-ul
    const dashboardElement = document.querySelector(".dashboard-container")
    if (!dashboardElement) {
      throw new Error("Dashboard container not found")
    }

    // 2. Configurează html2canvas pentru calitate înaltă
    const canvas = await html2canvas(dashboardElement, {
      scale: 2, // Dublează rezoluția pentru claritate
      useCORS: true,
      allowTaint: true,
      backgroundColor: "#f5f5f7",
      width: dashboardElement.scrollWidth,
      height: dashboardElement.scrollHeight,
      scrollX: 0,
      scrollY: 0,
    })

    // 3. Creează PDF-ul
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    })

    // 4. Calculează dimensiunile pentru A4
    const pdfWidth = pdf.internal.pageSize.getWidth()
    const pdfHeight = pdf.internal.pageSize.getHeight()
    const canvasWidth = canvas.width
    const canvasHeight = canvas.height

    // Calculează scala pentru a încăpea pe pagină
    const scale = Math.min(
      (pdfWidth - 20) / (canvasWidth / 2), // -20mm pentru margini
      (pdfHeight - 40) / (canvasHeight / 2), // -40mm pentru header și margini
    )

    const imgWidth = (canvasWidth / 2) * scale
    const imgHeight = (canvasHeight / 2) * scale

    // 5. Adaugă header cu informații
    addPDFHeader(pdf, {
      title: postTitle,
      platform: platform,
      postLink: postLink,
      exportDate: new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      }),
    })

    // 6. Adaugă imaginea dashboard-ului
    const imgData = canvas.toDataURL("image/png")
    pdf.addImage(imgData, "PNG", 10, 30, imgWidth, imgHeight)

    // 7. Adaugă footer cu statistici (dacă avem date)
    if (analysisData) {
      addPDFFooter(pdf, analysisData, pdfHeight)
    }

    // 8. Salvează PDF-ul
    pdf.save(filename)

    // 9. Afișează mesaj de succes
    showExportSuccess(filename)
  } catch (error) {
    console.error("❌ Error exporting PDF:", error)
    showExportError(error.message)
  } finally {
    showExportLoading(false)
  }
}

/**
 * Adaugă header-ul PDF-ului cu informații despre analiză
 */
function addPDFHeader(pdf, info) {
  // Logo/Title
  pdf.setFontSize(16)
  pdf.setFont("helvetica", "bold")
  pdf.text("Social Media Analysis Report", 10, 15)

  // Informații despre post
  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  pdf.text(`Platform: ${info.platform}`, 10, 22)
  pdf.text(`Generated: ${info.exportDate}`, 150, 22)

  if (info.postLink) {
    pdf.text(`URL: ${info.postLink.substring(0, 60)}${info.postLink.length > 60 ? "..." : ""}`, 10, 27)
  }

  // Linie de separare
  pdf.setDrawColor(200, 200, 200)
  pdf.line(10, 29, 200, 29)
}

/**
 * Adaugă footer cu statistici
 */
function addPDFFooter(pdf, analysisData, pageHeight) {
  const footerY = pageHeight - 20

  pdf.setDrawColor(200, 200, 200)
  pdf.line(10, footerY - 5, 200, footerY - 5)

  pdf.setFontSize(8)
  pdf.setFont("helvetica", "italic")
  pdf.text("Generated by likes2love Analytics Platform", 10, footerY)
  pdf.text(`Page 1 of 1`, 180, footerY)
}

/**
 * Afișează loading indicator pentru export
 */
function showExportLoading(show) {
  const existingLoader = document.querySelector(".pdf-export-loader")

  if (show && !existingLoader) {
    const loader = document.createElement("div")
    loader.className = "pdf-export-loader"
    loader.innerHTML = `
      <div class="loader-backdrop">
        <div class="loader-content">
          <div class="loader-spinner"></div>
          <p>Generating PDF...</p>
          <small>This may take a few seconds</small>
        </div>
      </div>
    `
    document.body.appendChild(loader)
  } else if (!show && existingLoader) {
    existingLoader.remove()
  }
}

/**
 * Afișează mesaj de succes
 */
function showExportSuccess(filename) {
  showToast(`PDF exported successfully! 📄\n${filename}`, "success")
}

/**
 * Afișează mesaj de eroare
 */
function showExportError(message) {
  showToast(`Failed to export PDF: ${message}`, "error")
}

/**
 * Afișează toast message
 */
function showToast(message, type) {
  const toast = document.createElement("div")
  toast.className = `export-toast ${type}`
  toast.innerHTML = `
    <div class="toast-content">
      <div class="toast-icon">
        ${type === "success" ? "✅" : "❌"}
      </div>
      <span>${message}</span>
    </div>
  `

  document.body.appendChild(toast)

  // Auto-remove după 4 secunde
  setTimeout(() => {
    toast.remove()
  }, 4000)
}

/**
 * Exportă doar datele analizei ca PDF (fără screenshot)
 */
export async function exportAnalysisDataToPDF(analysisData, postInfo) {
  try {
    const pdf = new jsPDF()

    // Header
    pdf.setFontSize(18)
    pdf.setFont("helvetica", "bold")
    pdf.text("Social Media Analysis Report", 20, 20)

    // Post info
    pdf.setFontSize(12)
    pdf.setFont("helvetica", "normal")
    pdf.text(`Platform: ${postInfo.platform}`, 20, 35)
    pdf.text(`Post: ${postInfo.title}`, 20, 45)
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, 20, 55)

    if (analysisData && analysisData.result) {
      const { percent_counts, average_scores } = analysisData.result

      pdf.setFontSize(14)
      pdf.setFont("helvetica", "bold")
      pdf.text("Sentiment Distribution:", 20, 75)

      pdf.setFontSize(11)
      pdf.setFont("helvetica", "normal")
      pdf.text(`Positive: ${percent_counts.positive}%`, 25, 85)
      pdf.text(`Neutral: ${percent_counts.neutral}%`, 25, 95)
      pdf.text(`Negative: ${percent_counts.negative}%`, 25, 105)

      pdf.setFont("helvetica", "bold")
      pdf.text("Average Scores:", 20, 125)

      pdf.setFont("helvetica", "normal")
      pdf.text(`Positive: ${average_scores.positive.toFixed(2)}`, 25, 135)
      pdf.text(`Neutral: ${average_scores.neutral.toFixed(2)}`, 25, 145)
      pdf.text(`Negative: ${average_scores.negative.toFixed(2)}`, 25, 155)
    }

    pdf.save(`analysis-data-${Date.now()}.pdf`)
    showExportSuccess("analysis-data.pdf")
  } catch (error) {
    showExportError(error.message)
  }
}
